### ISSUE TITLE
Q:what wrong is it in this error log?

### ISSUE THREAD

**Issue by wangyingjie55** [Mondego/SourcererCC#30]
search will be carried out with 2 nodes
loading previous run state
/home/michael/SourcererCC-master/clone-detector/scriptinator_metadata.scc doesn't exist, creating one with state EXECUTE_1
previous run state 0
running new command /home/michael/SourcererCC-master/clone-detector/execute.sh 1
Traceback (most recent call last):
  File "controller.py", line 180, in <module>
    controller.execute()
  File "controller.py", line 147, in execute
    "error in execute.sh script while preparing for init step.")
__main__.ScriptControllerException: error in execute.sh script while preparing for init step.

scriptinator_metadata.scc doesn't exist，why？ This is running on ubuntu,

**Comment by DehengYang** [comment]
I was once confronted with this problem. Maybe you can first make sure whether `realpath` command is available in your OS and then try to run ./cleanup, and finally run `python controller.py`
