### ISSUE TITLE
Why does the detection cost 3min?

### ISSUE THREAD

**Issue by wangyingjie55** [Mondego/SourcererCC#33]
There are only four files in the package, I think it will be very quick to detect clones,but it costs me 3 min and most in runnodes.sh. Is it normal or can I change some configurations to make it quick?

**Comment by zoubaihan** [comment]
Hi, I am also running this tool. When I was running python controller.py ,the following exception came out:

search will be carried out with 2 nodes
loading previous run state
previous run state 1
current state: 1
flushing current state 1
running new command /mnt/hgfs/G/SourcererCC-master/clone-detector/restore-gtpm.sh
running new command /mnt/hgfs/G/SourcererCC-master/clone-detector/runnodes.sh init 1
Traceback (most recent call last):
File "controller.py", line 180, in
controller.execute()
File "controller.py", line 144, in execute
raise ScriptControllerException("error during init.")
main.ScriptControllerException: error during init.

How can I deal with this trouble? Could you help me?
