### ISSUE TITLE
Why controller.py can not run? Could anybody help me?

### ISSUE THREAD

**Issue by zoubaihan** [Mondego/SourcererCC#46]
When I was running python controller.py ,the following exception came out:

search will be carried out with 2 nodes
loading previous run state
previous run state 1
current state:  1
flushing current state 1
running new command /mnt/hgfs/G/SourcererCC-master/clone-detector/restore-gtpm.sh
running new command /mnt/hgfs/G/SourcererCC-master/clone-detector/runnodes.sh init 1
Traceback (most recent call last):
  File "controller.py", line 180, in <module>
    controller.execute()
  File "controller.py", line 144, in execute
    raise ScriptControllerException("error during init.")
__main__.ScriptControllerException: error during init.

How can I deal with this trouble? Could you help me?

**Comment by Kyungchan95** [comment]
check line 22 of runnode.sh file. That code originally set 6g. So you should change that value.

**Comment by SolsticeG** [comment]
> check line 22 of runnode.sh file. That code originally set 6g. So you should change that value.
I have reset that value but the following exception still came out.

**Comment by yjkellyjoo** [comment]
having the same issue also... 😢

**Comment by yjkellyjoo** [comment]
solved the problem!
SourcererCC team did not specify that we had to build the clone-detector folder first before running it 😂

In SourcererCC/clone-detector/ folder, run the following command:
> ant clean cdi
Install ant if you do not have it.

Now that controller.py is running, I'm encountering another problem haha..
But hope this works for others!

**Comment by CharesFang** [comment]
> solved the problem! SourcererCC team did not specify that we had to build the clone-detector folder first before running it 😂↳
> 
> In '''SourcererCC/clone-detector/''' folder, run the following command:↳
> 
> > ant clean cdi↳
> 
> Install ant if you do not have it.↳
> 
> ======= I found out that the above command is already included in the runnodes.sh file line 6. It seems installing ant would suffice to fix the problem!↳

Thanks for your message! While I would suggest the authors should explicitly specify `ant` is the necessary dependency for running `SoucererCC`.
